# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# Pull config updates
if [ ! -f /tmp/jwolf-user-configs-fetched ]; then
    touch /tmp/jwolf-user-configs-fetched
    ~/Scripts/pull-configs > /dev/null
fi

