#!/bin/bash

# NeoVim
export config_nvim=~/AppData/Local/nvim

# Windows Terminal
export config_windows_terminal=~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/

# Git Bash
export config_git_bash=~

