#!/bin/bash
# Setup to use anaconda environment

anaconda_path="$HOME/AppData/Local/anaconda3"

# function to append path to $PATH
# Source: https://superuser.com/a/753948
pathprepend() {
  for ((i=$#; i>0; i--)); 
  do
    ARG=${!i}
    if [ -d "$ARG" ] && [[ ":$PATH:" != *":$ARG:"* ]]; then
        PATH="$ARG${PATH:+":$PATH"}"
    fi
  done
}

if [ -d "$anaconda_path" ]; then
    # Anaconda env setup script
    source /c/Users/jwolf/AppData/Local/Anaconda3/etc/profile.d/conda.sh

    # include important Anaconda dirs in path
        pathprepend "$anaconda_path" "$anaconda_path/Scripts" "$anaconda_path/Library"

    # So that the py and pip definitely link to the anaconda python environment
    alias py="python"
    alias pip="python -m pip"
fi
