#!/bin/bash
source ~/lib/bash_colors
source ~/lib/config_paths

# NeoVim
echo 
clr_bold clr_green "[NeoVim] $config_nvim"
git -C "$config_nvim" status

# Windows Terminal
echo 
clr_bold clr_green "[Windows Terminal] $config_windows_terminal"
git -C "$config_windows_terminal" status

# Git Bash
echo 
clr_bold clr_green "[Git Bash] $config_git_bash"
git -C "$config_git_bash" status

