#!/bin/bash
source ~/lib/bash_colors
source ~/lib/config_paths

# NeoVim
echo 
clr_bold clr_green "[NeoVim] $config_nvim"
git -C "$config_nvim" pull

# Windows Terminal
echo
clr_bold clr_green "[Windows Terminal] $config_windows_terminal"
git -C "$config_windows_terminal" pull

# Git Bash
echo
clr_bold clr_green "[Git Bash] ~"
git -C "$config_git_bash" pull

