#!/bin/bash
. ~/.bash_colors

# NeoVim
echo 
clr_bold clr_green "[NeoVim] ~/AppData/Local/nvim"
cd ~/AppData/Local/nvim
git pull

# Windows Terminal
echo
clr_bold clr_green "[Windows Terminal] ~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/"
cd ~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/
git pull

# Git Bash
echo
clr_bold clr_green "[Git Bash] ~"
cd ~
git pull

